// Enhanced mock data
export const clubsData = [
	{
		id: 1,
		name: "Science Club",
		overview:
			"Explore the wonders of science through experiments and discovery.",
		category: "academic",
		memberCount: 45,
		meetingSchedule: "Every Monday and Wednesday",
		location: "Science Building, Lab 101",
		nextEvent: "Guest Speaker: NASA Scientist",
		eventDate: "Next Monday, 3 PM",
		recentActivity: "Chemistry experiment showcase",
		images: [
			"../../public/images/image1.jpg",
			"../../public/images/image1.jpg",
			"../../public/images/image1.jpg",
		],
		tags: ["Research", "Experiments", "STEM"],
		upcomingEvents: [
			{
				title: "Guest Speaker: NASA Scientist",
				date: "Next Monday, 3 PM",
				location: "Auditorium A",
			},
			{
				title: "Science Fair Prep",
				date: "Next Wednesday, 4 PM",
				location: "Lab 101",
			},
		],
		achievements: [
			"First Place - Regional Science Fair 2024",
			"Published Research Paper in Student Journal",
		],
	},
	{
		id: 2,
		name: "Football Club",
		overview: "Join us for weekly football matches and training sessions.",
		category: "sports",
		memberCount: 32,
		meetingSchedule: "Tuesday and Thursday",
		location: "Main Sports Field",
		nextEvent: "Championship Match",
		eventDate: "This Saturday, 2 PM",
		recentActivity: "Won quarter-finals against State University",
		tags: ["Sports", "Team", "Competition"],
		upcomingEvents: [
			{
				title: "Championship Match",
				date: "This Saturday, 2 PM",
				location: "Main Sports Field",
			},
			{
				title: "Training Session",
				date: "Tuesday, 4 PM",
				location: "Training Ground",
			},
		],
		achievements: ["Regional Champions 2023", "Best Team Spirit Award"],
	},
	{
		id: 3,
		name: "Art Society",
		overview: "Unleash your creativity through various artistic mediums.",
		category: "arts",
		memberCount: 38,
		meetingSchedule: "Every Friday",
		location: "Arts Center, Studio 3",
		nextEvent: "Annual Art Exhibition",
		eventDate: "Next Month, May 15",
		recentActivity: "Watercolor Workshop",
		tags: ["Creative", "Exhibition", "Workshop"],
		upcomingEvents: [
			{
				title: "Annual Art Exhibition",
				date: "May 15",
				location: "Gallery Hall",
			},
			{
				title: "Life Drawing Session",
				date: "This Friday, 2 PM",
				location: "Studio 3",
			},
		],
		achievements: ["Best Club Exhibition 2023", "Community Outreach Award"],
	},
	{
		id: 4,
		name: "Mathletes",
		overview: "Compete in mathematics competitions and solve complex problems.",
		category: "academic",
		memberCount: 25,
		meetingSchedule: "Monday and Friday",
		location: "Mathematics Building, Room 204",
		nextEvent: "Math Olympiad Preparation",
		eventDate: "Tomorrow, 4 PM",
		recentActivity: "Won State Mathematics Competition",
		tags: ["Competition", "Problem Solving", "Academic"],
		upcomingEvents: [
			{
				title: "Math Olympiad Preparation",
				date: "Tomorrow, 4 PM",
				location: "Room 204",
			},
			{
				title: "Mock Competition",
				date: "Next Friday, 3 PM",
				location: "Main Hall",
			},
		],
		achievements: [
			"State Mathematics Champions 2024",
			"Perfect Score in Regional Competition",
		],
	},
	{
		id: 5,
		name: "Photography Club",
		overview: "Capture moments and master photography techniques.",
		category: "arts",
		memberCount: 42,
		meetingSchedule: "Every Tuesday",
		location: "Arts Building, Room 204",
		nextEvent: "Photo Walk in the Park",
		eventDate: "Next Tuesday, 4 PM",
		recentActivity: "Studio Lightning Workshop",
		tags: ["Creative", "Technical", "Outdoor"],
		upcomingEvents: [
			{
				title: "Photo Walk in the Park",
				date: "Next Tuesday, 4 PM",
				location: "Central Park",
			},
			{
				title: "Portrait Photography Workshop",
				date: "In two weeks, 3 PM",
				location: "Studio 2",
			},
		],
		achievements: [
			"Best Photography Exhibition 2023",
			"Community Documentation Award",
		],
	},
	{
		id: 6,
		name: "Coding Ninjas",
		overview: "Master programming skills and build amazing projects.",
		category: "academic",
		memberCount: 56,
		meetingSchedule: "Every Wednesday",
		location: "Tech Hub, Lab 305",
		nextEvent: "Hackathon Prep Session",
		eventDate: "This Friday, 5 PM",
		recentActivity: "Web Development Workshop",
		tags: ["Programming", "Technology", "Innovation"],
		upcomingEvents: [
			{
				title: "Hackathon Prep Session",
				date: "This Friday, 5 PM",
				location: "Lab 305",
			},
			{
				title: "Code Review Workshop",
				date: "Next Wednesday, 4 PM",
				location: "Tech Hub",
			},
		],
		achievements: [
			"First Place - University Hackathon",
			"Best Technical Innovation Award",
		],
	},
];
