export const courses = [
	{
		id: 1,
		title: "Introduction to Computer Science",
		code: "CS101",
		instructor: "Dr. John Doe",
		progress: 60,
		department: "Computer Science",
		credits: 3,
		image: "/images/image1.jpg",
	},
	{
		id: 2,
		title: "Calculus I",
		instructor: "Prof. Jane Smith",
		progress: 30,
		department: "Mathematics",
		credits: 4,
		image: "/images/image2.jpg",
	},
	{
		id: 3,
		title: "World History",
		instructor: "Dr. Bob Johnson",
		progress: 45,
		department: "History",
		credits: 3,
		image: "/images/image3.jpg",
	},
	{
		id: 4,
		title: "Introduction to Psychology",
		instructor: "Dr. Alice Williams",
		progress: 20,
		department: "Psychology",
		credits: 3,
		image: "/images/image4.jpg",
	},
	{
		id: 5,
		title: "Organic Chemistry",
		instructor: "Prof. Charlie Brown",
		progress: 70,
		department: "Chemistry",
		credits: 4,
		image: "/images/image5.jpg",
	},
	{
		id: 6,
		title: "Microeconomics",
		instructor: "Dr. Diana Ross",
		progress: 50,
		department: "Economics",
		credits: 3,
		image: "/images/image6.jpg",
	},
];
